"""
Notification module for jobflow-ai.

Formats email content and handles notifications.
The actual email sending is handled by GitHub Actions.
"""

from datetime import date
from pathlib import Path


def format_email_body(results: list, budget_summary: str = "") -> str:
    """
    Format results as an email-friendly markdown body.

    Args:
        results: List of processed job results
        budget_summary: Optional budget summary string

    Returns:
        Formatted markdown string for email body
    """
    today = date.today().strftime("%B %d, %Y")
    count = len(results)

    lines = [
        f"# jobflow-ai Results - {today}",
        "",
        f"Found and processed **{count}** job opportunities.",
        "",
    ]

    if not results:
        lines.extend([
            "No new relevant jobs found today.",
            "",
            "This could mean:",
            "- No new postings matching your criteria in the last 24 hours",
            "- Jobs were filtered out by rule-based or AI filtering",
            "",
            "Check the discovery_log.json for details on what was found and filtered.",
        ])
        return "\n".join(lines)

    lines.append("## Top Opportunities")
    lines.append("")

    for i, result in enumerate(results, 1):
        company = result.get('company', 'Unknown')
        role = result.get('role', 'Unknown')
        job_url = result.get('job_url', '#')
        analysis = result.get('analysis', {})
        targets = result.get('outreach_targets', [])

        lines.extend([
            f"### #{i}: {role} @ {company}",
            f"**Link**: [{job_url}]({job_url})",
            "",
        ])

        # Key points from analysis
        strengths = analysis.get('candidate_strengths', [])
        if strengths:
            lines.append(f"**Your Strengths**: {', '.join(strengths[:3])}")

        requirements = analysis.get('key_requirements', [])
        if requirements:
            lines.append(f"**Key Requirements**: {', '.join(requirements[:3])}")

        gaps = analysis.get('candidate_gaps', [])
        if gaps:
            lines.append(f"**Gaps to Address**: {', '.join(gaps[:2])}")

        lines.append("")

        # Outreach contacts
        if targets:
            lines.append("**Outreach Contacts**:")
            lines.append("")
            lines.append("| Name | Type | LinkedIn |")
            lines.append("|------|------|----------|")
            for target in targets[:3]:
                name = target.get('name', 'N/A')
                conn_type = target.get('connection_type', 'N/A')
                url = target.get('linkedin_url', '#')
                lines.append(f"| {name} | {conn_type} | [Profile]({url}) |")
            lines.append("")

        # Files
        slug = result.get('slug', '')
        if slug:
            lines.append(f"**Files**: `{slug}/resume.tex`, `{slug}/outreach.md`")
            lines.append("")

        lines.append("---")
        lines.append("")

    # Budget summary
    if budget_summary:
        lines.extend([
            "## Cost Summary",
            budget_summary,
            "",
        ])

    # Footer
    lines.extend([
        "---",
        "",
        "*Generated by [jobflow-ai](https://github.com/yourusername/jobflow-ai)*",
        "",
        "View full results in the GitHub Actions artifacts.",
    ])

    return "\n".join(lines)


def format_summary_for_slack(results: list) -> str:
    """
    Format results for Slack notification (shorter format).

    Args:
        results: List of processed job results

    Returns:
        Slack-formatted message
    """
    count = len(results)

    if not results:
        return "jobflow-ai: No new relevant jobs found today."

    lines = [
        f"*jobflow-ai*: Found {count} job opportunities!",
        "",
    ]

    for i, result in enumerate(results, 1):
        company = result.get('company', 'Unknown')
        role = result.get('role', 'Unknown')
        job_url = result.get('job_url', '#')
        lines.append(f"{i}. <{job_url}|{role} @ {company}>")

    return "\n".join(lines)


def save_notification_content(results: list, output_dir: str, budget_summary: str = "") -> Path:
    """
    Save notification content to file.

    Args:
        results: List of processed job results
        output_dir: Output directory
        budget_summary: Optional budget summary

    Returns:
        Path to saved notification file
    """
    today = date.today().isoformat()
    notify_path = Path(output_dir) / today / "notification.md"
    notify_path.parent.mkdir(parents=True, exist_ok=True)

    content = format_email_body(results, budget_summary)
    notify_path.write_text(content, encoding='utf-8')

    return notify_path
